// Needs a production build WITHOUT Supabase keys served on :3100 (npx next build && npx next start -p 3100).
// Set CHROMIUM_PATH if Playwright cannot find a browser.
import os from "node:os";
import path from "node:path";
import { chromium as pw } from "playwright";
const TMP = os.tmpdir() + path.sep;
const chromium = { launch: (o = {}) => pw.launch({ ...o, executablePath: process.env.CHROMIUM_PATH || undefined }) };
import fs from "fs";
const S = TMP;
const b = await chromium.launch({});
const ctx = await b.newContext({ acceptDownloads: true });
const page = await ctx.newPage();
const errs = []; page.on("pageerror", e => errs.push(String(e)));
await page.goto("http://localhost:3100/");
await page.waitForSelector(".topic-card");
await page.evaluate(() => localStorage.setItem("algebraQuestState_v1", JSON.stringify({ xp: 230, bestStreak: 4, mastered: { 1: [0, 1] }, customProblems: {}, theme: "forest", name: "Sam", masteredDates: {}, avatar: "root" })));
await page.reload(); await page.waitForSelector(".topic-card");
console.log("level chip:", (await page.textContent(".stat-chip")).trim());
const [dl] = await Promise.all([page.waitForEvent("download"), page.click("#exportBtn")]);
await dl.saveAs(S + "backup.json");
console.log("download:", dl.suggestedFilename(), "xp in file:", JSON.parse(fs.readFileSync(S + "backup.json", "utf8")).state.xp);
await page.click("#resetBtn"); await page.click("#resetBtn");
console.log("xp after reset:", await page.evaluate(() => JSON.parse(localStorage.getItem("algebraQuestState_v1")).xp));
await page.setInputFiles("#importFile", S + "backup.json");
await page.waitForTimeout(400);
console.log("after import [xp,name,theme,dom theme]:", await page.evaluate(() => { const s = JSON.parse(localStorage.getItem("algebraQuestState_v1")); return JSON.stringify([s.xp, s.name, s.theme, document.documentElement.dataset.theme]); }));
fs.writeFileSync(S + "bad.json", "{nope");
await page.setInputFiles("#importFile", S + "bad.json");
await page.waitForTimeout(300);
console.log("bad file message:", await page.textContent("#backupMsg"));
await page.reload(); await page.waitForTimeout(2000);
console.log("service worker active:", await page.evaluate(async () => !!(await navigator.serviceWorker.getRegistration())?.active));
await page.reload(); await page.waitForTimeout(1000);
await ctx.setOffline(true);
await page.reload(); await page.waitForSelector(".topic-card", { timeout: 8000 });
console.log("offline: cards", await page.$$eval(".topic-card", e => e.length), "| xp kept:", (await page.textContent(".stat-chip")).trim());
await ctx.setOffline(false);
const man = await page.evaluate(() => fetch("/manifest.webmanifest").then(r => r.json()));
console.log("manifest:", man.name, man.display, man.icons.length, "icons");
console.log("page errors:", errs);
await b.close();
